title: fox10301          # Название сайта (используется в <title>)
url: "https://person10301.github.io"  # Базовый URL

markdown: kramdown       # Рендеринг markdown
permalink: pretty        # Красивые URL (без .html)
